# Generated by Django 4.2.4 on 2023-08-27 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_order_is_returned_returnorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnorder',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
